name: Restricted Branch Check

on:
  workflow_call:
    secrets:
      JIRA_URL:
        required: true
      JIRA_USERNAME:
        required: true
      JIRA_API_TOKEN:
        required: true

jobs:
  restricted-branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout workflow repo
        uses: actions/checkout@v4
        with:
          repository: udkyo/gha-test
          ref: main
          path: gha-test
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: latest
      - name: Run restricted branch check
        run: uv run ./gha-test/.github/scripts/restricted-branch-check.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.event.repository.full_name }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
