name: Restricted Branch Check

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
      JIRA_URL:
        required: true
      JIRA_USERNAME:
        required: true
      JIRA_API_TOKEN:
        required: true

jobs:
  restricted-branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: latest
      - name: Run restricted branch check
        run: uv run ./.github/scripts/restricted-branch-check.py
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.event.repository.full_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
