name: Restricted Branch Check

on:
  workflow_call:
    inputs:
      head_ref:
        description: 'PR head branch'
        required: true
        type: string
      head_repo:
        description: 'PR head repo'
        required: true
        type: string
      pr_number:
        description: 'PR number'
        required: true
        type: string
    secrets:
      JIRA_URL:
        required: true
      JIRA_USERNAME:
        required: true
      JIRA_API_TOKEN:
        required: true

jobs:
  restricted-branch-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.head_repo }}
          ref: ${{ inputs.head_ref }}
          path: code
      - name: Checkout workflow repo
        uses: actions/checkout@v4
        with:
          repository: udkyo/gha-test
          ref: main
          path: workflow
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: latest
      - name: Run restricted branch check
        run: uv run ./workflow/.github/scripts/restricted-branch-check.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ inputs.pr_number }}
          REPO: ${{ inputs.head_repo }}
          GITHUB_BASE_REF: ${{ github.event.pull_request.base.ref }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
